In [2]:
import faiss
faiss.__version__

'1.13.2'

In [3]:
bio_text = """
Making an Impact
Helping Millions of Students Succeed
Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances.

In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world.

The Entrepreneur and Teacher: Sudhanshu's Dual Legacy
Sudhanshu's journey isn't just one of entrepreneurial success; it's also a story of dedication to teaching. Throughout his career, he has remained a passionate educator, constantly looking for ways to empower others through knowledge. Whether teaching courses in Big Data, Data Science, or programming, Sudhanshu has always sought to make complex subjects accessible to learners at all levels.

His commitment to affordable education has earned him the respect and admiration of countless students. Many credit Sudhanshu with changing their lives, helping them secure jobs, improve their skills, and break free from the limitations of their backgrounds.

Th
e Journey

Early Life and the Power of Education

Rising Through the Ranks of the Tech World

The Birth of iNeuron: Democratizing Education

The Foundation of Euron: Expanding the Mission

Early Life and the Power of Education
Sudhanshu Kumar's life is a story of triumph over adversity, driven by the belief in the transformative power of education. Born in Jamshedpur, Jharkhand, India, to a family of very modest means, Sudhanshu's early years were marked by financial hardship. His surroundings offered little opportunity, and resources were limited, yet he understood from a young age that education could be his ticket out of poverty.

While many would have been daunted by the lack of support and opportunity, Sudhanshu was relentless in his pursuit of knowledge. He knew that education had the power to change lives, and he was determined to leverage it to create a better future for himself and his family. Despite the numerous challenges along the way, Sudhanshu excelled academically, eventually earning a degree in Computer Science and Engineering (CSE).
"""

In [4]:
import requests 
import json
import os 
import numpy as np
# Broken down the text into smaller chunks
def chunk_text(text, chunk_size=50, overlap=5):
    words = text.split()
    chunks = []
    start = 0
    while start < len(words):
        end = min(start + chunk_size, len(words))
        chunks.append(" ".join(words[start:end]))
        start += chunk_size - overlap
    return chunks

In [5]:
chunks = chunk_text(bio_text)
print(f"Total chunks created: {len(chunks)}")
chunks

Total chunks created: 9


["Making an Impact Helping Millions of Students Succeed Sudhanshu's commitment to affordable education wasn't just a business strategy—it was his life's mission. Over the years, iNeuron has helped over 1.5 million students from 34+ countries, providing them with the skills they need to succeed in today's competitive job market. Many",
 "today's competitive job market. Many of these students, like Sudhanshu himself, came from disadvantaged backgrounds. They saw iNeuron as a lifeline—an opportunity to rise above their circumstances. In 2022, iNeuron was acquired by PhysicsWallah in a deal worth ₹250 crore. While this acquisition was a significant milestone, Sudhanshu remained focused",
 "significant milestone, Sudhanshu remained focused on his mission. Even after the acquisition, iNeuron continued to offer some of the most affordable and accessible tech courses in the world. The Entrepreneur and Teacher: Sudhanshu's Dual Legacy Sudhanshu's journey isn't just one of entrepreneurial succes

In [6]:
API_URL = "https://api.euron.one/api/v1/euri/embeddings"
API_KEY = "euri-eca149f81167bfd14dcbf6025b8bb834fec9aa6b728b4e8bac19531047ecb9f0"
API_MODEL = "text-embedding-3-small"
headers = {
    "Content-Type": "application/json",
    "Authorization": f"Bearer {API_KEY}"
}

In [7]:
# Generate embeddings for each chunk of text
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

all_embeddings = []
for i, chunk in enumerate(chunks):
    payload = {
        "model": API_MODEL,
        "input": chunk
    }
    response = requests.post(API_URL, headers=headers, data=json.dumps(payload), verify=False)
    result = response.json()
    all_embeddings.append(result["data"][0]["embedding"])

In [8]:
all_embeddings

[[0.00028474937,
  -0.01390119,
  0.055709872,
  0.04107289,
  0.033531036,
  -0.044489063,
  0.016857492,
  0.09743972,
  -0.02719798,
  -0.0020070006,
  0.05649822,
  -0.057812132,
  -0.06669418,
  -0.0058961804,
  0.012843491,
  -0.018631274,
  -0.008330203,
  -0.0535025,
  0.016410762,
  0.051741857,
  0.050795842,
  0.054868966,
  0.02255987,
  -0.0046742423,
  0.07394697,
  -0.04469929,
  0.022756957,
  0.0053739003,
  -0.014886624,
  -0.047300834,
  -0.0031665282,
  -0.009775505,
  -0.043411653,
  -0.0042636446,
  -0.016949465,
  0.004979727,
  -0.022389062,
  0.012245661,
  -0.015819501,
  0.0057615046,
  0.0033192704,
  -0.014255946,
  0.03529168,
  0.021955471,
  -0.04212402,
  0.006057135,
  -0.032979194,
  -0.013874912,
  0.0092499405,
  0.0762069,
  -0.022047445,
  0.03529168,
  0.03960131,
  -0.026514746,
  -0.0019133844,
  0.01792176,
  0.008231659,
  0.031586446,
  -0.094654225,
  -0.033425923,
  0.04109917,
  -0.015477885,
  0.06853365,
  0.04217658,
  -0.013125981,
  

In [9]:
len(all_embeddings), len(all_embeddings[0])

(9, 1536)

In [10]:
# Convert the list of embeddings to a NumPy array
embeddings_array =np.array(all_embeddings, dtype=np.float32)
embeddings_array



array([[ 0.00028475, -0.01390119,  0.05570987, ..., -0.01592461,
        -0.00744331,  0.00277235],
       [-0.03135502, -0.04274139,  0.01195286, ..., -0.02200799,
         0.02139902,  0.02054929],
       [-0.0068724 , -0.00218016,  0.04815887, ..., -0.03376327,
         0.00073459,  0.02359785],
       ...,
       [ 0.00034703, -0.01026421,  0.00563141, ..., -0.02826451,
        -0.00751487, -0.02097085],
       [-0.010022  , -0.01289087, -0.00252295, ..., -0.00508399,
        -0.03998644, -0.01160241],
       [-0.00150543, -0.02032089,  0.01566804, ..., -0.02907391,
        -0.01435701,  0.00868876]], shape=(9, 1536), dtype=float32)

In [11]:
# Create a FAISS index of same dimensionality(1536 here) and add the embeddings
# We use IndexFlatL2 for simplicity, which performs exact nearest neighbor search using L2 distance.
base_index = faiss.IndexFlatL2(embeddings_array.shape[1])
base_index.add(embeddings_array)

In [12]:
# Save the FAISS index to disk
faiss.write_index(base_index, "faiss_index.faiss")

In [13]:
# Querying the FAISS index
query_text = "What is Sudhanshu's background?"

In [14]:
# Function to get embedding for the query
def get_query_embedding(query):
    payload = {
        "model": API_MODEL,
        "input": query
    }
    response = requests.post(API_URL, headers=headers, data=json.dumps(payload), verify=False)
    result = response.json()
    return np.array(result["data"][0]["embedding"], dtype=np.float32)


In [15]:
# Calling the function to get the query embedding
query_embedding = get_query_embedding(query_text)
query_embedding

array([-0.04787971, -0.00472044,  0.02169748, ..., -0.0068163 ,
        0.00459304, -0.01065763], shape=(1536,), dtype=float32)

In [16]:
# Performing the search in the FAISS index for the top 3 most similar chunks
base_index.search(np.array([query_embedding]), k=3)

(array([[0.7476543 , 0.80220735, 0.80449307]], dtype=float32),
 array([[6, 8, 4]]))

In [17]:
print(f"Query: {query_text}")
chunks[6], chunks[8], chunks[4]

Query: What is Sudhanshu's background?


("by the belief in the transformative power of education. Born in Jamshedpur, Jharkhand, India, to a family of very modest means, Sudhanshu's early years were marked by financial hardship. His surroundings offered little opportunity, and resources were limited, yet he understood from a young age that education could be his",
 'leverage it to create a better future for himself and his family. Despite the numerous challenges along the way, Sudhanshu excelled academically, eventually earning a degree in Computer Science and Engineering (CSE).',
 'at all levels. His commitment to affordable education has earned him the respect and admiration of countless students. Many credit Sudhanshu with changing their lives, helping them secure jobs, improve their skills, and break free from the limitations of their backgrounds. Th e Journey Early Life and the Power of')