In [21]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-eca149f81167bfd14dcbf6025b8bb834fec9aa6b728b4e8bac19531047ecb9f0"

payload = {
    "input": "Sunil is learning to use the Euron API for generating embeddings.",
    "model": "text-embedding-3-small"
}   
response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"}, verify=False)
result1 = response.json()["data"][0]["embedding"]
print(result1)
print(len(result1))

c:\Users\611005937\OneDrive - BT Plc\D Drive\Sunil_GIT_Workspaces\Generative-AI_Workspace\myDevEnv\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.euron.one'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(


[-0.022991791, -0.034467362, 0.04237968, -0.016203996, 0.007837802, -0.015553669, 0.034873817, 0.053570736, -0.00077649794, -0.022788564, 0.020553062, -0.07321605, -0.04229839, 0.0088268425, 0.021135647, -0.00011410371, -0.02318147, 0.020160155, -0.041377094, 0.012362999, 0.059613366, -0.03755642, 0.023682764, 0.0323538, 0.03601189, -0.032949932, 0.035090595, 0.043599047, -0.023018887, -0.059667557, 0.019875638, -0.030673785, 0.012423967, 0.014971084, -0.021230487, -0.01343333, 0.011265571, 0.031215725, -0.017640136, -0.0027757473, 0.008677809, -0.03378994, -0.022219528, 0.024184057, -0.011157183, 0.03126992, -0.04966877, -0.034440268, 0.06161854, 0.009240071, -0.03351897, 0.0016969487, -0.034331877, -0.0027757473, -0.04885586, 0.00010494789, -0.011292668, 0.04205452, -0.06839278, -0.0057208505, 0.009504267, -0.019564021, 0.0037563194, 0.015675604, -0.0007866593, 0.0070926356, -0.05050878, 0.021677587, -0.02677182, -0.002618246, 0.036797702, -0.0045489063, 0.028641513, -0.019089825, 0.

In [22]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-eca149f81167bfd14dcbf6025b8bb834fec9aa6b728b4e8bac19531047ecb9f0"

payload = {
    "input": "Sunil works at BT as a Software Engineer.",
    "model": "text-embedding-3-small"
}   
response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"}, verify=False)
result2 = response.json()["data"][0]["embedding"]
print(result2)

c:\Users\611005937\OneDrive - BT Plc\D Drive\Sunil_GIT_Workspaces\Generative-AI_Workspace\myDevEnv\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.euron.one'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(


[-0.03910098, -0.04099574, 0.016905205, -0.01975965, -0.0010227403, -0.0021608272, 0.02864288, 0.04067584, -0.030513033, -0.037919827, -0.005078329, -0.011017912, -0.011983748, 0.044760652, 0.013607829, -0.0060810754, -0.012845003, 0.0021239163, -0.044908296, -0.011645398, 0.06437266, 0.017951015, 0.019156773, 0.042447567, 0.025690006, -0.018590804, -0.0027144912, 0.012648145, 0.0066993334, -0.04104495, 0.012438983, -0.020608602, 0.018873788, 0.023758335, 0.024865663, 0.0066993334, 0.050198864, 0.0100336205, 0.016609918, -0.010968697, 0.0019455135, -0.028667487, -0.028495237, 0.026329795, -0.016302327, -0.005675055, -0.0415371, 0.03823972, 0.06555381, -0.024730321, 0.010488856, -0.005918052, 0.024976395, 0.012149847, -0.020460958, 0.025862258, 0.02479184, 0.05512032, -0.013976938, -0.008575639, 0.036664855, -0.007505222, -0.015330339, 0.018357035, -0.044908296, -0.014038457, -0.060779996, 0.020214885, -0.01631463, -0.037107788, 0.007197631, 0.04377636, 0.051429227, 0.009935192, 0.05251

In [23]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-eca149f81167bfd14dcbf6025b8bb834fec9aa6b728b4e8bac19531047ecb9f0"

payload = {
    "input": "What is Sunil doing at work?",
    "model": "text-embedding-3-small"
}   
response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"}, verify=False)
queryInp = response.json()["data"][0]["embedding"]
print(queryInp)

c:\Users\611005937\OneDrive - BT Plc\D Drive\Sunil_GIT_Workspaces\Generative-AI_Workspace\myDevEnv\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.euron.one'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(


[-0.047438692, -0.0033867133, 0.045970354, 0.017747154, 0.031315185, -0.001079195, 0.036030818, 0.019723766, 0.009643044, -0.053170867, 0.00048488769, -0.02189804, -0.013511556, 0.010659588, 0.017351832, -0.0363979, -0.033376507, -0.03927811, -0.0522108, -0.0071228635, 0.08708388, 0.026472485, -0.018806053, 0.029846845, 0.02747491, -0.015375219, -0.030157454, 0.034901325, 0.039023973, -0.05946779, -0.0012265585, -0.030863388, 0.0049944757, 0.019752003, 0.011520825, 0.005463921, 0.026656028, -0.011323164, -0.0058980696, -0.0027743164, 0.022138057, -0.026246587, -0.019526105, -0.008894755, 0.018678986, 0.004066174, -0.05613579, 0.020712072, 0.07098862, -0.009932476, -0.0096289255, -0.012346767, 0.02357816, 0.018820172, -0.015502287, -0.008591204, 0.011852614, 0.036764987, -0.044982046, -0.02114975, 0.002959624, -0.0363979, -0.017097695, 0.022363955, -0.035720207, -0.0063181, -0.037499156, 0.036906175, -0.05274731, -0.03159756, 0.037922718, 0.011167859, 0.06443756, -0.026938401, 0.0452644

In [24]:
import numpy as np
statement1 = np.array(result1)
statement2 = np.array(result2) 
question = np.array(queryInp)
statement1, statement2, question


(array([-0.02299179, -0.03446736,  0.04237968, ..., -0.00606634,
         0.00133114, -0.02175888], shape=(1536,)),
 array([-0.03910098, -0.04099574,  0.0169052 , ...,  0.01369396,
         0.03203868, -0.00654554], shape=(1536,)),
 array([-0.04743869, -0.00338671,  0.04597035, ...,  0.01973788,
         0.02751727, -0.01410454], shape=(1536,)))

In [25]:
dist_question_statement1 = np.linalg.norm(question - statement1)
dist_question_statement2 = np.linalg.norm(question - statement2)
print(dist_question_statement1)
print(dist_question_statement2)

1.0184191037820696
0.7966658477295419
